ingress:
  enabled: false
  awsApiDebug: false
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsVpcRegion: ""
  awsVpcId: ""
  namespace: kube-system
  class: alb
  clusterName: default
  host: ""
  tags: "app=akeneo"
  addressType: ipv4
  