nameOverride: null

imagePullSecrets: null

efs:
  enabled: false
  # existingClaim: akeneo-pvc
  replicaCount: 1
  revisionHistoryLimit: 10
  image:
    repository: quay.io/external_storage/efs-provisioner
    tag: v2.1.0-k8s1.11
    pullPolicy: IfNotPresent  
  busyboxImage:
    repository: gcr.io/google_containers/busybox
    tag: 1.27
    pullPolicy: IfNotPresent
## Configure provisioner
## https://github.com/kubernetes-incubator/external-storage/tree/master/aws/efs#deployment
##
  efsFileSystemId: fs-12345678
  awsRegion: us-east-2
  path: /
  provisionerName: example.com/aws-efs
  storageClass:
    name: efs
    isDefault: false
    gidAllocate:
      enabled: true
      gidMin: 40000
      gidMax: 50000
    reclaimPolicy: Delete
  # Don't use /
  containerMountPaths: {}
    # - /media 
  ## Enable RBAC
  ##
  rbac:
    # Specifies whether RBAC resources should be created
    create: true

  ## Create or use ServiceAccount
  ##
  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    create: true
    # The name of the ServiceAccount to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  ## Annotations to be added to deployment
  ##
  podAnnotations: {}
    # iam.amazonaws.com/role: efs-provisioner-role

  ## Node labels for pod assignment
  ##
  nodeSelector: {}

  # Affinity for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  ## Configure resources
  ##
  resources: {}
    # To specify resources, uncomment the following lines, adjust them as necessary,
    # and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 200m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  priorityClassName: ""

hostpath:
  enabled: false
  path: /hostpath
  type: DirectoryOrCreate
  containerMountPaths:
    - "/srv/pim/web/media"
    - "/srv/pim/app/file_storage"
    - "/tmp/pim"
    - "/var/import"
    - "/var/export"
    - "/var/logs"
  provisionerName: example.com/hostpath
  storageClass:
    name: hostpath
    isDefault: false
    gidAllocate:
      enabled: true
      gidMin: 40000
      gidMax: 50000
    reclaimPolicy: Delete

images:
 php:
  repo: hevelop/ak-php
  tag: latest
 phpcli:
  repo: hevelop/ak-php
  tag: latest
 httpd:
  repo: hevelop/ak-httpd
  tag: latest

ingress:
  enabled: false
  controller: false
  awsApiDebug: false
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsVpcRegion: ""
  awsVpcId: ""
  namespace: kube-system
  class: alb
  clusterName: default
  host: ""
  tags: "app=akeneo"
  addressType: ipv4
  annotations: {}

akeneo:
  parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: akeneo_pim
    database_user: akeneo_pim
    database_password: akeneo_pim
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    product_index_name: akeneo_pim_product
    product_model_index_name: akeneo_pim_product_model
    product_and_product_model_index_name: akeneo_pim_product_and_product_model
    index_hosts: ''

  redis:
    enabled: false
    default:
      host: null
      db: 0
    cache:
      host: null
      db: 1
    session:
      host: null
      db: 2
    framework_cache:
      host: null
      db: 0
    sessionPrefix: pim

phpfpm:
  volumePermissionEnabled: false
  userPermissions: 1000
  listenPort: 9001
  requests:
    enabled: true
    cpu: "500m"
    memory: "384Mi"
  limits:
    enabled: true
    cpu: "1500m"
    memory: "1Gi"
phpcli:
  enabled: false
  requests:
    enabled: true
    cpu: "500m"
    memory: "384Mi"
  limits:
    enabled: true
    cpu: "1000m"
    memory: "1Gi"
httpd:
  requests:
    enabled: true
    cpu: "50m"
    memory: "256Mi"
  limits:
    enabled: true
    cpu: "400m"
    memory: "256Mi"