ingress:
  enabled: false
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
  awsVpcRegion: ""
  awsVpcId: ""
  namespace: kube-system
  class: alb
  clusterName: default
  host: ""
  tags: "app=akeneo"
  listenPorts:
    HTTP: 80
    HTTPS: 443
  addressType: ipv4
  