kind: ConfigMap
apiVersion: v1
metadata:
  name: akeneo-parameters-yml
  labels:
    name: akeneo-parameters-yml
data:
  parameters.yml: |
    parameters:
      {{- range $key, $value := .Values.configmap.akeneo.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}