 kind: ConfigMap
 apiVersion: v1
 metadata:
   name: {{ template "akeneo.fullname" . }}-akeneo-parameters-yml
   labels:
     name: {{ template "akeneo.fullname" . }}-akeneo-parameters-yml
 data:
   parameters.yml: |
     parameters:
      {{- range $key, $value := .Values.akeneo.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}