{{- if .Values.ingress.controller }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "akeneo.fullname" . }}-alb-ingress-secrets
stringData:
  # AWS key id for authenticating with the AWS API.
  # This is only here for examples. It's recommended you instead use
  # a project like kube2iam for granting access.
  {{- if .Values.ingress.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.ingress.awsAccessKeyId }}
  {{- end }}

  # AWS key secret for authenticating with the AWS API.
  # This is only here for examples. It's recommended you instead use
  # a project like kube2iam for granting access.
  {{- if .Values.ingress.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ingress.awsSecretAccessKey }}
  {{- end }}
{{- end }}