{{- $akeneo_fullname := include "akeneo.fullname" . }}
{{- $existingClaim := .Values.efs.existingClaim | default (printf "%s-efs-pvc" (include "akeneo.fullname" .)) }}
{{- range $job := .Values.jobs }}
{{- $cron_image := printf "%s/%s:%s" $job.registry $job.repository $job.tag -}}
{{- if $job.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $akeneo_fullname }}-cron-{{ $job.name }}
  labels:
    app: {{ $akeneo_fullname }}-cron-{{ $job.name }}
spec:
  schedule: {{ $job.schedule | quote }}
  {{- if has $job.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ $job.startingDeadlineSeconds }}
  {{- end }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ $job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $akeneo_fullname }}-cron-{{ $job.name }}
        spec:
          {{- if $.Values.pullSecrets }}
          imagePullSecrets:
            {{- range $.Values.pullSecrets }}
            - name: {{ . }}
            {{- end}}
          {{- end }}
          containers:
            - name: {{ $akeneo_fullname }}-cronjob-{{ $job.name }}
              image: {{ $cron_image }}
              imagePullPolicy: {{ $job.pullPolicy | quote }}
              command: {{ $job.command }}
              volumeMounts:
              {{- if or $.Values.efs.enabled $.Values.efs.existingClaim }}                
                {{- range $index, $val := $.Values.efs.containerMountPaths }}
                - mountPath: "{{ $val }}"
                  subPath: {{ (trimPrefix "/" $val) }}
                  name: efs
                {{- end }}
              {{- end }}
              resources:
{{ toYaml $job.resources | indent 16 }}
          volumes:          
          {{- if $existingClaim }}
          - name: efs
            persistentVolumeClaim:
              claimName: {{ $existingClaim }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy | default "Never" }}
{{- end }}
{{- end }}