{{- if and (.Values.efs.enabled) (not .Values.efs.existingClaim) }}
{{- if .Values.efs.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "akeneo.serviceAccountName" . }}
  labels:
    app: {{ template "akeneo.name" . }}
    chart: {{ template "akeneo.chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.efs.annotations | indent 4 }}
{{- end }}
{{- end }}