{{- if and (.Values.hostpath.enabled) (not .Values.hostpath.existingClaim) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: {{ .Values.hostpath.storageClass.name }}
  labels:
    app: {{ template "akeneo.name" . }}
    chart: {{ template "akeneo.chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.hostpath.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{ toYaml .Values.hostpath.annotations | indent 4 }}
{{- end }}
provisioner: {{ .Values.hostpath.provisionerName }}
reclaimPolicy: {{ .Values.hostpath.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
{{- end }}