apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
      tier: frontend
  template:
    metadata:
      labels:
        app: httpd
        tier: frontend
    spec:
      containers:
      - name: httpd
        image: hevelop/ak-httpd
        ports:
        - containerPort: 80