apiVersion: v1
kind: Service
metadata:
  name: {{ template "akeneo.fullname" . }}-service-httpd
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  selector:
    app: {{ template "akeneo.fullname" . }}-httpd
    tier: {{ template "akeneo.fullname" . }}-frontend
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80