{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "akeneo.fullname" . }}-httpd
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: {{ .Values.ingress.tags }}
    {{- if .Values.ingress.listenPorts }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.listenPorts }}
    {{- end }}
    alb.ingress.kubernetes.io/ip-address-type: {{ .Values.ingress.addressType }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: httpd
              servicePort: 80
{{- end }}