apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    tier: frontend
spec:
  selector:
    app: httpd
    tier: frontend
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80