apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-httpd
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-httpd
      tier: {{ template "akeneo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-httpd
        tier: {{ template "akeneo.fullname" . }}-frontend
    spec:
      containers:
      - name: httpd
        image: hevelop/ak-httpd:1.3
        ports:
        - containerPort: 80
      restartPolicy: Always