apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-httpd
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-httpd
      tier: {{ template "akeneo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-httpd
        tier: {{ template "akeneo.fullname" . }}-frontend
    spec:
      # volumes:
      #   - name: vhost-conf
      #     configMap:
      #       name: {{ template "akeneo.fullname" . }}-vhost-conf
      #   - name: httpd-conf
      #     configMap:
      #       name: {{ template "akeneo.fullname" . }}-httpd-conf
      containers:
      - name: httpd
        image: "{{ .Values.images.httpd.repo -}} : {{- .Values.images.httpd.tag }}"
        ports:
        - containerPort: 80
        # volumeMounts:
        #   - name: vhost-conf
        #     mountPath: /usr/local/apache2/conf/vhost.conf
        #     subPath: vhost.conf
        #   - name: httpd-conf
        #     mountPath: /usr/local/apache2/conf/httpd.conf
        #     subPath: httpd.conf
      restartPolicy: Always