apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    tier: frontend
  {{- if .Values.ingress.enabled }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  {{- end }}
spec:
  selector:
    app: httpd
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80