{{- $userPermissions := .Values.phpfpm.userPermissions }}
{{- if .Values.efs.enabled }}
apiVersionssss: apps/v88888
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-php
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-php
      tier: {{ template "akeneo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-php
        tier: {{ template "akeneo.fullname" . }}-frontend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets | quote }}
      {{- end }}
      volumes:
        {{- if .Values.efs.enabled }}
        - name: efs
          persistentVolumeClaim:
            claimName: {{ .Values.efs.existingClaim | default (printf "%s-efs-pvc" (include "akeneo.fullname" .)) }}
        {{- end }}
        {{- if .Values.hostpath.enabled }}
        - name: hostpath
          hostPath:
            # directory location on host
            path: {{ .Values.hostpath.path }}
            # this field is optional
            type: Directory
        {{- end }}
      {{- if or .Values.efs.enabled .Values.efs.existingClaim .Values.hostpath.enabled }}
      {{- if .Values.phpfpm.volumePermissionEnabled }}
      initContainers:
      - name: volume-permissions
        image: alpine
        command: ["/bin/sh","-c"]
        args:
        - |-
          chown -c {{ .Values.phpfpm.userPermissions }}:{{ .Values.phpfpm.userPermissions }} /efs &&
        {{- if or .Values.efs.enabled .Values.efs.existingClaim }}
        {{- range $index, $val := .Values.efs.containerMountPaths }}
          chown -c {{ $userPermissions }}:{{ $userPermissions }} {{ $val }} &&
        {{- end }}
        {{- end }}
        {{- if .Values.hostpath.enabled }}
        {{- range $index, $val := .Values.hostpath.containerMountPaths }}
          chown -c {{ $userPermissions }}:{{ $userPermissions }} {{ $val }} &&
        {{- end }}
        {{- end }}
          ls -la /srv/pim
        volumeMounts:
        {{- if or .Values.efs.enabled .Values.efs.existingClaim }}
        - mountPath: /efs
          name: efs
        {{- range $index, $val := .Values.efs.containerMountPaths }}
        - mountPath: {{ $val }}
          subPath: {{ (trimPrefix "/" $val) }}
          name: efs
        {{- end }}
        {{- end }}
        {{- if .Values.hostpath.enabled }}
        - mountPath: /hostpath
          name: hostpath
        {{- range $index, $val := .Values.hostpath.containerMountPaths }}
        - mountPath: {{ $val }}
          subPath: {{ (trimPrefix "/" $val) }}
          name: hostpath
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: php
          image: "{{ .Values.images.php.repo -}} : {{- .Values.images.php.tag }}"
          env:
          - name: COMPOSER_HOME
            value: /home/docker/.composer
          workingDir: /srv/pim
          ports:
          - containerPort: {{ .Values.phpfpm.listenPort }}
          {{- if or (eq .Values.phpfpm.limits.enabled true) (eq .Values.phpfpm.requests.enabled true) }}
          resources:
            {{- if .Values.phpfpm.limits.enabled }}
            limits:
              cpu: {{ .Values.phpfpm.limits.cpu }}
              memory: {{ .Values.phpfpm.limits.memory }}
            {{- end }}
            {{- if .Values.phpfpm.requests.enabled}}
            requests:
              cpu: {{ .Values.phpfpm.requests.cpu }}
              memory: {{ .Values.phpfpm.requests.memory }}
            {{- end }}
          {{- else }}
          resources: {}
          {{- end }}
          volumeMounts:
            {{- if .Values.efs.enabled }}
            {{- range $index, $val := .Values.efs.containerMountPaths }}
            - mountPath: {{ $val }}
              subPath: {{ (trimPrefix "/" $val) }}
              name: efs
            {{- end }}
            {{- end }}
            {{- if .Values.hostpath.enabled }}
            {{- range $index, $val := .Values.hostpath.containerMountPaths }}
            - mountPath: {{ $val }}
              subPath: {{ (trimPrefix "/" $val) }}
              name: hostpath
            {{- end }}
            {{- end }}
      restartPolicy: Always