{{- if .Values.phpcli.enabled }}
{{- include "efs.list" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-php-cli
  labels:
    tier: {{ template "akeneo.fullname" . }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-php-cli
      tier: {{ template "akeneo.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-php-cli
        tier: {{ template "akeneo.fullname" . }}-worker
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets | quote }}
      {{- end }}
      volumes:
        {{- include "efs.list.volumes" . | indent 8 }}
        {{- if .Values.hostpath.enabled }}
        - name: hostpath
          persistentVolumeClaim:
            claimName: {{ .Values.hostpath.existingClaim | default (printf "%s-hostpath-pvc" (include "akeneo.fullname" .)) }}
        {{- end }}
      containers:
        - name: php-cli
          image: "{{ .Values.images.phpcli.repo -}} : {{- .Values.images.phpcli.tag }}"
          env:
          - name: COMPOSER_HOME
            value: /home/docker/.composer
          workingDir: /srv/pim
          ports:
          - containerPort: {{ .Values.phpfpm.listenPort }}
          {{- if or (eq .Values.phpfpm.limits.enabled true) (eq .Values.phpfpm.requests.enabled true) }}
          resources:
            {{- if .Values.phpfpm.limits.enabled }}
            limits:
              cpu: {{ .Values.phpfpm.limits.cpu }}
              memory: {{ .Values.phpfpm.limits.memory }}
            {{- end }}
            {{- if .Values.phpfpm.requests.enabled}}
            requests:
              cpu: {{ .Values.phpfpm.requests.cpu }}
              memory: {{ .Values.phpfpm.requests.memory }}
            {{- end }}
          {{- else }}
          resources: {}
          {{- end }}
          volumeMounts:
            {{- include "efs.list.volumeMounts" . | indent 12 }}
            {{- if .Values.hostpath.enabled }}
            {{- range $index, $val := .Values.hostpath.containerMountPaths }}
            - mountPath: {{ $val }}
              subPath: {{ (trimPrefix "/" $val) }}
              name: hostpath
            {{- end }}
            {{- end }}
      restartPolicy: Always
{{- end }}