apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-php
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-php
      tier: {{ template "akeneo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-php
        tier: {{ template "akeneo.fullname" . }}-frontend
    spec:
      # volumes:
      #   - name: akeneo-parameters
      #     configMap:
      #       name: {{ template "akeneo.fullname" . }}-akeneo-parameters-yml
      #   - name: akeneo-config-prod
      #     configMap:
      #       name: {{ template "akeneo.fullname" . }}-akeneo-config-prod-yml
      containers:
      - name: php
        image: "{{ .Values.images.php.repo -}} : {{- .Values.images.php.tag }}"
        env:
        - name: COMPOSER_HOME
          value: /home/docker/.composer
        workingDir: /srv/pim
        ports:
        - containerPort: 9001
        # volumeMounts:
        #   - name: akeneo-parameters
        #     mountPath: /srv/pim/app/config/parameters.yml
        #     subPath: parameters.yml
        #   - name: akeneo-config-prod
        #     mountPath: /srv/pim/app/config/config_prod.yml
        #     subPath: config_prod.yml
      restartPolicy: Always