{{- if .Values.efs.enabled }}
apiVersionssss: apps/v88888
{{- end }}
{{- if .Values.phpworker.enabled }}
apiVersionssss: apps/v88888
  {{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-php-worker
  labels:
    tier: {{ template "akeneo.fullname" . }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-php-worker
      tier: {{ template "akeneo.fullname" . }}-worker
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-php-worker
        tier: {{ template "akeneo.fullname" . }}-worker
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets | quote }}
      {{- end }}
      volumes:
        {{- if .Values.efs.enabled }}
        - name: efs
          persistentVolumeClaim:
            claimName: {{ .Values.efs.existingClaim | default (printf "%s-efs-pvc" (include "akeneo.fullname" .)) }}
        {{- end }}
      containers:
        - name: php-worker
          image: "{{ .Values.images.phpworker.repo -}} : {{- .Values.images.phpworker.tag }}"
          command:
            - su
            - www-data
            - -s
            - /bin/sh
            - -c
            - {{ .Values.phpworker.command }}
          env:
          - name: COMPOSER_HOME
            value: /home/docker/.composer
          workingDir: /srv/pim
          ports:
          - containerPort: {{ .Values.phpfpm.listenPort }}
          volumeMounts:
            {{- if .Values.efs.enabled }}
            {{- range $index, $val := .Values.efs.containerMountPaths }}
            - mountPath: {{ $val }}
              subPath: {{ (trimPrefix "/" $val) }}
              name: efs
            {{- end }}
            {{- end }}
      restartPolicy: Always