apiVersion: v1
kind: Service
metadata:
  name: {{ template "akeneo.fullname" . }}-service-php
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  selector:
    app: {{ template "akeneo.fullname" . }}-php
    tier: {{ template "akeneo.fullname" . }}-frontend
  ports:
  - protocol: TCP
    port: {{ .Values.phpfpm.listenPort }}