apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: frontend
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      volumes:
        - name: akeneo-parameters
          configMap:
            name: akeneo-parameters-yml
        - name: akeneo-config-prod
          configMap:
            name: akeneo-config-prod-yml
      containers:
      - name: php
        image: hevelop/ak-php:1.2
        env:
        - name: COMPOSER_HOME
          value: /home/docker/.composer
        workingDir: /srv/pim
        ports:
        - containerPort: 9001
        volumeMounts:
          - name: akeneo-parameters
            mountPath: /srv/pim/app/config/parameters.yml
            subPath: parameters.yml
          - name: akeneo-config-prod
            mountPath: /srv/pim/app/config/config_prod.yml
            subPath: config_prod.yml
      restartPolicy: Always