{{- if .Values.efs.enabled }}
apiVersionssss: apps/v88888
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "akeneo.fullname" . }}-php
  labels:
    tier: {{ template "akeneo.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "akeneo.fullname" . }}-php
      tier: {{ template "akeneo.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "akeneo.fullname" . }}-php
        tier: {{ template "akeneo.fullname" . }}-frontend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets | quote }}
      {{- end }}
      volumes:
        - name: akeneo-parameters
          configMap:
            name: {{ template "akeneo.fullname" . }}-akeneo-parameters-yml
        {{- if .Values.akeneo.redis.enabled }}
        - name: akeneo-config-prod
          configMap:
            name: {{ template "akeneo.fullname" . }}-akeneo-config-prod-yml
        {{- end }}
        {{- if .Values.efs.enabled }}
        - name: efs
          persistentVolumeClaim:
            claimName: {{ .Values.efs.existingClaim | default (printf "%s-efs-pvc" (include "akeneo.fullname" .)) }}
        {{- end }}
      containers:
        - name: php
          image: "{{ .Values.images.php.repo -}} : {{- .Values.images.php.tag }}"
          env:
          - name: COMPOSER_HOME
            value: /home/docker/.composer
          workingDir: /srv/pim
          ports:
          - containerPort: 9001
          volumeMounts:
            - name: akeneo-parameters
              mountPath: /srv/pim/app/config/parameters.yml
              subPath: parameters.yml
            {{- if .Values.akeneo.redis.enabled }}
            - name: akeneo-config-prod
              mountPath: /srv/pim/app/config/config_prod.yml
              subPath: config_prod.yml
            {{- end }}
            {{- if .Values.efs.enabled }}
            {{- range $index, $val := .Values.efs.containerMountPaths }}
            - mountPath: {{ $val }}
              subPath: {{ (trimPrefix "/" $val) }}
              name: efs
            {{- end }}
            {{- end }}
      restartPolicy: Always