{{- if .Values.ingress.controller }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "akeneo.fullname" . }}-alb-ingress-controller
  name: {{ template "akeneo.fullname" . }}-alb-ingress-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
{{- end }}
---
{{- if .Values.ingress.controller }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "akeneo.fullname" . }}-alb-ingress-controller
  name: {{ template "akeneo.fullname" . }}-alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "akeneo.fullname" . }}-alb-ingress-controller
subjects:
  - kind: ServiceAccount
    name: {{ template "akeneo.fullname" . }}-alb-ingress
    namespace: {{ .Values.ingress.namespace }}
{{- end }}
---
{{- if .Values.ingress.controller }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "akeneo.fullname" . }}-alb-ingress-controller
  name: {{ template "akeneo.fullname" . }}-alb-ingress
  namespace: {{ .Values.ingress.namespace }}
{{- end }}